### ISSUE TITLE
Star breaks down with new installation 

### ISSUE THREAD

**Issue by AndranikIvanov** [bihealth/seasnap-pipeline#10]
STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
Dec 01 15:08:36 ..... started STAR run
Dec 01 15:08:36 ..... loading genome
Dec 01 15:08:53 ..... started mapping
Dec 01 15:31:21 ..... finished mapping
Dec 01 15:31:23 ..... finished successfully
+ cut -f1,4 mapping/star/4_Hypo_OP13/all_mates/out/ReadsPerGene.out.tab
+ mv mapping/star/4_Hypo_OP13/all_mates/out/ReadsPerGene.out.tab mapping/star/4_Hypo_OP13/all_mates/out/4_Hypo_OP13.ReadsPerGene.out.tab
+ mv mapping/star/4_Hypo_OP13/all_mates/out/Log.final.out mapping/star/4_Hypo_OP13/all_mates/out/4_Hypo_OP13.Log.final.out
++ expr 8 / 2
++ expr 10000 / 8
+ samtools sort -@ 4 -m 1250M -T mapping/star/4_Hypo_OP13/all_mates/out/sort -o mapping/star/4_Hypo_OP13/all_mates/out/star.4_Hypo_OP13.all_mates.bam mapping/star/4_Hypo_OP13/all_mates/out/Aligned.out.bam
[bam_sort_core] merging from 20 files and 4 in-memory blocks...
+ mv mapping/star/4_Hypo_OP13/all_mates/out/Aligned.out.bam mapping/star/4_Hypo_OP13/all_mates/out/star.4_Hypo_OP13.all_mates.unsorted.bam
+ picard MarkDuplicates I=mapping/star/4_Hypo_OP13/all_mates/out/star.4_Hypo_OP13.all_mates.bam O=mapping/star/4_Hypo_OP13/all_mates/out/4_Hypo_OP13.mdup.bam M=mapping/star/4_Hypo_OP13/all_mates/out/4_Hypo_OP13.metrics.out TMP_DIR=mapping/star/4_Hypo_OP13/all_mates/out
INFO    2021-12-01 15:33:37     MarkDuplicates  

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MarkDuplicates -I mapping/star/4_Hypo_OP13/all_mates/out/star.4_Hypo_OP13.all_mates.bam -O mapping/star/4_Hypo_OP13/all_mates/out/4_Hypo_OP13.mdup.bam -M mapping/star/4_Hypo_OP13/all_mates/out/4_Hypo_OP13.metrics.out -TMP_DIR mapping/star/4_Hypo_OP13/all_mates/out
**********

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at picard.cmdline.CommandLineProgram.getCommandLineParserForArgs(CommandLineProgram.java:398)
        at picard.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:348)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:223)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
        at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:576)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:601)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:588)
        at org.broadinstitute.barclay.argparser.LegacyCommandLineArgumentParser.<clinit>(LegacyCommandLineArgumentParser.java:97)
        ... 5 more
(END)

**Comment by messersc** [comment]
This looks like a problem with two java installations in the conda env, where we have 1.7 and 1.8 at the same time and picard does not use the correct one. We will need to untangle that.
