### ISSUE TITLE
single cell pipeline fails at rule all due to problem with "csv-table" and snakemake version

### ISSUE THREAD

**Issue by mmilek** [bihealth/seasnap-pipeline#16]
Using current conda envrinoment (conda_env.yaml), the single-cell pipeline on branch `feature_cellranger_multi` fails due to problems with csv-table directive path.
```
RuleException:
SystemMessage in line 94 of /data/gpfs-1/home/users/milekm_c/seasnap-pipeline/sc_pipeline.snake:
:17: (SEVERE/4) Problems with "csv-table" directive path:
[Errno 2] No such file or directory: '../sc_analysis/pipeline_report/all_samples.all_mates/out/pipeline_report.all_samples.all_mates.summary.csv'.
```

Most likely cause is that the current yaml file leads to the installation of higher version of snakemake (7.1.0), which fails with the csv-table. Workaround is to use the `conda_env_mapping_sc.yaml` on `development` branch, which will install snakemake 5.14.0.

**Comment by mmilek** [comment]
might not be installed at all?
working environment:
```
(sea_snap_bo_final) [milekm_c@hpc-cpu-219 python3.7]$ python -c 'import sphinx'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx'
```
broken environment:
```
(sea_snap) [milekm_c@hpc-cpu-219 python3.7]$ python -c 'import sphinx'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx'
```
